### ISSUE TITLE
Implementation of Dice Loss

### ISSUE THREAD

**Issue by layadas** [YilmazKadir/Segmentation_Losses#1]
The implementation of Dice loss divides the intersection by the sum of [all targets and inputs](https://github.com/YilmazKadir/Segmentation_Losses/blob/main/losses/dice.py#L23). But, according to equation 7 of the [paper](https://arxiv.org/pdf/2312.05391.pdf), the sum in the denominator should only be over the class under consideration. So, should the denominator have `input_c` and `target_c` instead of `input` and `target` respectively?

**Comment by moeinheidari7829** [comment]
Thank you for your interest in our code and paper!

Equation 7 of the paper is correct, and the implementation you discussed is also calculated per class (as it loops over num_classes):
https://github.com/YilmazKadir/Segmentation_Losses/blob/8e4a89575a40940f1e32573f69d7e77e6e4ed175/losses/dice.py#L18
